import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import pfp from "../src/assets/portrait.jpg";
import github from "../src/assets/github.svg";
import linkedin from "../src/assets/linkedin.svg";
import twitter from "../src/assets/twitter.svg";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kushagra Sarathe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fav icon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <FontAwesomeIcon icon={faFaceRelieved} /> */}
        <div>
          <h1 className={styles.title}>Hey there, I&#x27;m</h1>
          <div className={styles.pfp}>
            <Image className={styles.round} src={pfp} alt="profile image" />
          </div>
          <h1 className={styles.title}>
            <span className={styles.highlight}>Kushagra Sarathe &#128075;</span>
            ,
          </h1>
        </div>
        <h1 className={`${styles.name} ${styles.typing_effect}`}>
          I&#x27;m a{" "}
          <span className={styles.highlight}>
            Front-end Developer &#128187;
          </span>
        </h1>

        <div className={styles.connect}>
          <div className={styles.socials}>
            <a
              href="https://github.com/kushagrasarathe"
              target="_blank"
              rel="noopener noreferrer"
            >
              <div className={styles.icon}>
                <Image src={github} alt="profile image" />
              </div>
            </a>
            <a
              href="https://linkedin.com/in/kushagra-sarathe"
              target="_blank"
              rel="noopener noreferrer"
            >
              <div className={styles.icon}>
                <Image src={linkedin} alt="profile image" />
              </div>
            </a>
            <a
              href="https://twitter.com/kushagrasarathe"
              target="_blank"
              rel="noopener noreferrer"
            >
              <div className={styles.icon}>
                <Image src={twitter} alt="profile image" />
              </div>
            </a>
          </div>
        </div>
      </main>
    </div>
  );
}
